### ISSUE TITLE
Foreign Key cannot be inverted to entity type after upgrade from 5.0.0-preview.8.20407.4 to 5.0.1

### ISSUE THREAD

**Issue by groege** [dotnet/EntityFramework.Docs#3004]
## File a bug

I have this (some code has been removed):
This worked on 5.0.0-preview.8.20407.4 without any Issues, but is broken on 5.0.1

```C#
public partial class OrderConcurrencyConfiguration : IEntityTypeConfiguration<OrderConcurrency>
    {
        public void Configure(EntityTypeBuilder<OrderConcurrency> builder)
        {
            builder.ToTable(@"OrderConcurrencies");
            builder.Property(x => x.TransportOrderGuid).HasColumnName(@"TransportOrderGuid").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"TransportOrderGuid");
            builder.HasOne(x => x.Order).WithOne(op => op.Concurrency).OnDelete(DeleteBehavior.Cascade).IsRequired(true).HasForeignKey(typeof(Order), @"TransportOrderGuid");

            //some more assignments
        }
    }
```
```C#
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> builder)
        {
            builder.ToTable(@"Orders");
            builder.Property(x => x.TransportOrderGuid).HasColumnName(@"TransportOrderGuid").IsRequired().ValueGeneratedNever();
           
            //tons of other assignments
        }
    }
```

Everything works fine with the prelease Version but it would be nice to upgrade to an actually released verson.

### Include stack traces

> The foreign key {'OrderTransportOrderGuid'} on entity type 'OrderConcurrency' cannot be inverted to entity type 'Order' since it was configured as required before the dependent side was configured. Configure the foreign key property or the principal key before configuring the foreign key as required. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The foreign key {'OrderTransportOrderGuid'} on entity type 'OrderConcurrency' cannot be inverted to entity type 'Order' since it was configured as required before the dependent side was configured. Configure the foreign key property or the principal key before configuring the foreign key as required. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReplaceForeignKey(ConfigurationSource configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 oldNameDependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 isRequiredDependent, Nullable`1 isOwnership, Nullable`1 deleteBehavior, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Boolean oldRelationshipInverted)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasEntityTypes(EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 principalEndConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasEntityTypes(EntityType principalEntityType, EntityType dependentEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, Func`3 hasForeignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, IReadOnlyList`1 foreignKeyPropertyNames)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder`2.HasForeignKey(Type dependentEntityType, String[] foreignKeyPropertyNames)
   at FreightExchange.Model.OrderConfiguration.Configure(EntityTypeBuilder`1 builder) in C:\Users\haberl\source\repos\carriermobile\FreightExchange.Model\Data\FreightExchange.Order.Configuration.Generated.cs:line 382
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at FreightExchange.Model.FreightExchangeDb.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\haberl\source\repos\carriermobile\FreightExchange.Model\FreightExchange.FreightExchangeDb.Generated.cs:line 420
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at FreightExchange.Startup.ConfigureServices(IServiceCollection services) in C:\Users\haberl\source\repos\carriermobile\FreightExchange\Startup.cs:line 208
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at FreightExchange.Program.BuildWebHost(String[] args) in C:\Users\haberl\source\repos\carriermobile\FreightExchange\Program.cs:line 27
   at FreightExchange.Program.Main(String[] args) in C:\Users\haberl\source\repos\carriermobile\FreightExchange\Program.cs:line 23

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.MemberIdentity?, Microsoft.EntityFrameworkCore.Metadata.MemberIdentity?, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property>, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property>, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property>, bool?, bool?, bool?, bool?, Microsoft.EntityFrameworkCore.DeleteBehavior?, bool, Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource?, bool)
    Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasEntityTypes(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource?, Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource)
    Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasEntityTypes(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, Microsoft.EntityFrameworkCore.Metadata.ConfigurationSource)
    Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, string, System.Func<Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder>)
    Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType, string, System.Collections.Generic.IReadOnlyList<string>)
    Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder<TEntity, TRelatedEntity>.HasForeignKey(System.Type, string[])
    FreightExchange.Model.OrderConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<FreightExchange.Model.Order>) in FreightExchange.Order.Configuration.Generated.cs
    Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration<TEntity>(Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>)
    FreightExchange.Model.FreightExchangeDb.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder) in FreightExchange.FreightExchangeDb.Generated.cs
    Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(Microsoft.EntityFrameworkCore.ModelBuilder, Microsoft.EntityFrameworkCore.DbContext)
    ...
    [Call Stack Truncated]
```

[stacktrace.txt](https://github.com/dotnet/efcore/files/5796499/stacktrace.txt)

EF Core version: 5.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (5.0.1)
Target framework: net5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.0 Preview 2.0

**Comment by groege** [comment]
> Note from triage: we should document this as a breaking change; moving to the docs repo.
> 
> @groege Are you having issues following the guidance in the message? If so, can you be more specific about what those issues are?

Yes, I don't understand why this exception happens, because the doc is saying that one should supply the foreign key, which is happening... I think it should work this way... 
```
builder.HasOne(x => x.Order)
    .WithOne(op => op.Concurrency)
    .OnDelete(DeleteBehavior.Cascade)
    .IsRequired(true)
    //i think this should work, what am I doing wrong? (it is actually genereated Code, so fixing will be more work since I have to adapt the Template
    .HasForeignKey(typeof(Order), @"TransportOrderGuid");
```

**Comment by ajcvickers** [comment]
@groege And if you move `IsRequired` to after `HasForeignKey`?

**Comment by AndriySvyryd** [comment]
Documented at https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#required-dependent

**Comment by groege** [comment]
> @groege And if you move `IsRequired` to after `HasForeignKey`?

@ajcvickers Thanks for the tip, sadly the problem still persists, no change in the exception
```
builder.HasOne(x => x.Order)
    .WithOne(op => op.Concurrency)
    .OnDelete(DeleteBehavior.Cascade)
    .HasForeignKey(typeof(Order), @"TransportOrderGuid")
    .IsRequired(true);
```

**Comment by groege** [comment]
> Documented at https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#required-dependent

@AndriySvyryd can we reopen, since it seems not to be the main issue here?

**Comment by groege** [comment]
Should I send you the project? (I could zip the model projects with its dependencies - what was the url to the ms forum where I can upload a file hidden from the public?)

**Comment by AndriySvyryd** [comment]
@groege Can you instead create a minimal repro project and attach it in a comment?

**Comment by groege** [comment]
@AndriySvyryd @ajcvickers 

So I found the issue by doing the minimal repro
[ConsoleApp12.zip](https://github.com/dotnet/EntityFramework.Docs/files/5812876/ConsoleApp12.zip)

This throws an exception
```
            modelBuilder.ApplyConfiguration<Order>(new OrderConfiguration());
            modelBuilder.ApplyConfiguration<OrderConcurrency>(new OrderConcurrencyConfiguration());
```
This does not...
```
            modelBuilder.ApplyConfiguration<Order>(new OrderConfiguration());
            modelBuilder.ApplyConfiguration<OrderConcurrency>(new OrderConcurrencyConfiguration());
```

So here is the big issue, I use a graphical table editor (devart EntityDeveloper) which generates all the classes, I only add some custom overrides in some cases when necessary...
How can I detect in which order the configurations have to be done? Because I will have to let the generator know somehow which should come first...

To be honest I think EF should be able to find the right order itself. I would like to create a feature request for this but have no idea how to call it ==> "Find the order for type configurations depending on relations"? 
Is there anything like this planned?

**Comment by groege** [comment]
So i found out the order in wich OrderConcurrencyConfiguration  and OrderConfiguration are registered matters.

In this case OrderConcurrencyConfiguration needs to be defined before OrderConfiguration  to work...

[ConsoleApp12.zip](https://github.com/dotnet/EntityFramework.Docs/files/5813013/ConsoleApp12.zip)

**Comment by AndriySvyryd** [comment]
@groege It's throwing because in `OrderConfiguration` you are calling `IsRequired` before `HasForeignKey`

**Comment by groege** [comment]
> @groege It's throwing because in `OrderConfiguration` you are calling `IsRequired` before `HasForeignKey`

🙈 Sorry - and thanks for all the help!
