### ISSUE TITLE
Unable to start app when linker set to full linking mode

### ISSUE THREAD

**Issue by gyb001** [dotnet/EntityFramework.Docs#3204]
How to reproduce. 
Download this project: [EntityFramework.Docs/samples/core/Xamarin/](https://github.com/dotnet/EntityFramework.Docs/tree/main/samples/core/Xamarin), or any Xamarin Sqlite EF core repo like:  [medium.com example](https://medium.com/codechem/using-entityframework-core-and-sqlite-with-xamarin-forms-45de7a926b71)

In android option set linker to : Sdk And User Assemblies.  [Image](https://imgur.com/a/cHDaVUq)

Run the android app.

Tried in Debug an Release mode,
VS 19 Enterprise preview, or 19 community

Exception: 
`04-16 08:57:35.790	pixel_2_pie_9_0_-_api_28	Info	16316	MonoDroid	android.runtime.JavaProxyThrowable: System.InvalidOperationException: A suitable constructor for type 'Microsoft.EntityFrameworkCore.Internal.DbSetInitializer' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache lifetime, System.Type serviceType, System.Type implementationType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x0004a] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor, System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain, System.Int32 slot) [0x00073] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x00018] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x0002e] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory+<>c__DisplayClass7_0.<GetCallSite>b__0 (System.Type type) [0x00000] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <c72658f647bc485bbfb8c9fcaa790862>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x00014] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor (System.Type serviceType) [0x0000c] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <c72658f647bc485bbfb8c9fcaa790862>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) [0x00013] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) [0x00008] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <fe25f472c9454a3da38f5915de5dca62>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService (System.IServiceProvider provider, System.Type serviceType) [0x00034] in <502e95c8ec6749ccbea1beb8e4f9bc9c>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T] (System.IServiceProvider provider) [0x0000e] in <502e95c8ec6749ccbea1beb8e4f9bc9c>:0 
  at Microsoft.EntityFrameworkCore.DbContext..ctor (Microsoft.EntityFrameworkCore.DbContextOptions options) [0x00063] in <819bbdbc85a640d3aa62acf566d8c5b8>:0 
  at Microsoft.EntityFrameworkCore.DbContext..ctor () [0x00006] in <819bbdbc85a640d3aa62acf566d8c5b8>:0 
  at XamarinEFCore.DatabaseContext.ApplicationDbContext..ctor () [0x00000] in <bc9d1c1c306c45c6a01583d3de68576b>:0 
  at XamarinEFCore.App..ctor () [0x0000f] in <bc9d1c1c306c45c6a01583d3de68576b>:0 
  at XamarinEFCore.Android.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00027] in <245316efdf1b45f7891f88b4899a52f8>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <44e54a86dea24313a2bdb807df77c27a>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
	at crc64b4240de972c2a2fa.MainActivity.n_onCreate(Native Method)
	at crc64b4240de972c2a2fa.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

I added this for the SkipLinkList: Microsoft.EntityFrameworkCore.Internal.DbSetInitializer 
then: 
`'A suitable constructor for type 'Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal.SqliteLoggingDefinitions' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.'
`
After added the  'Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal.SqliteLoggingDefinitions' to SkipList, i got again this exception 

`System.InvalidOperationException: 'A suitable constructor for type 'Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal.SqliteLoggingDefinitions' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.'
`

Android.csproj:
`  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <AndroidLinkSkip>System.Core;Microsoft.EntityFrameworkCore;Microsoft.EntityFrameworkCore.Internal.DbSetInitializer;Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal.SqliteLoggingDefinitions</AndroidLinkSkip>
  </PropertyGroup>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf41872-597e-d846-0e54-e6e84f00ac72
* Version Independent ID: 19da55b4-6887-cb39-a87e-bb71c433de8b
* Content: [Getting Started with EF Core and Xamarin - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/xamarin)
* Content Source: [entity-framework/core/get-started/xamarin.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/get-started/xamarin.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by gyb001** [comment]
I asked this in stackoverflow in the past: [Link ](https://stackoverflow.com/questions/64024969/how-to-use-microsoft-entityframeworkcore-sqlite-in-xamarin-with-full-linking-l)

**Comment by ajcvickers** [comment]
This is tracked by https://github.com/dotnet/efcore/issues/10963
