### ISSUE TITLE
This article is so old, DbContext fails...

### ISSUE THREAD

**Issue by kkkristo** [dotnet/EntityFramework.Docs#4188]
Working on VS 2022 and following instructions you get message:

Unhandled exception. System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_StateManager()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.EntryWithoutDetectChanges(TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at CodeFirstNewDatabaseSample.Program.Main(String[] args) in C:\Users\Lenovo\source\repos\CodeFirstNewDatabaseSample\CodeFirstNewDatabaseSample\Program.cs:line 17

Is there any up-to-date tutorial teaching step by step how to start work with EntityFramwerok?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8be815-df51-dc77-fb5b-ccfa7f742e10
* Version Independent ID: 353c54e3-b7c9-fcdd-ca71-2a11beab19fd
* Content: [Code First to a New Database - EF6](https://learn.microsoft.com/en-gb/ef/ef6/modeling/code-first/workflows/new-database)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/new-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/modeling/code-first/workflows/new-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
