### ISSUE TITLE
How to remove all previous migrations and create a new "Initial" migration from existing stable DB?

### ISSUE THREAD

**Issue by khteh** [dotnet/EntityFramework.Docs#4273]
## Ask a question
As the number of migrations grow overtime, I would like to remove all the previous migration files from `Migrations` folder and create a new "Initial" migration from existing DB after the schema has firmed up - without any impact to the production DB. I am thinking of using the following steps:

(1) Backup
(2) `DELETE FROM public."__EFMigrationsHistory";`
(3) `rm -rf migrations`
(4) `dotnet-ef migrations add initial -c <context>`
(5) `dotnet-ef update database -c <context>`

Would this work?

**Comment by roji** [comment]
As the docs say, you need to generate a SQL script after creating your new initial migration (`dotnet ef migrations script`). The last line of this script is the SQL to insert that single row; it looks something like the following:

```sql
INSERT INTO [__EFMigrationsHistory] ([MIGRATIONID], [PRODUCTVERSION])
VALUES (N'20230302095549_initial', N'7.0.2');
```

I've submitted [#4272](https://github.com/dotnet/EntityFramework.Docs/pull/4272/files) to make the instructions a little clearer.

**Comment by khteh** [comment]
Is there any specific location where the generated script should be put? Thanks.

**Comment by roji** [comment]
No, you're supposed to generate it only in order to get that line out.

**Comment by khteh** [comment]
I have 2 contexts. The second context fails:
```
$ dotnet-ef database update -c KyberlifeIAMDbContext
Build started...
Build succeeded.
DesignTimeDbContextFactory.Create(string): Connection string: Host=kyberlife.cluster-c6pe9efbeiq6.ap-southeast-1.rds.amazonaws.com; Database=Kyberlife; Username=guest; Password=P@$$w0rd
Applying migration '20230303062854_Initial'.
Failed executing DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);
Npgsql.PostgresException (0x80004005): 42P07: relation "AspNetRoles" already exists
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "AspNetRoles" already exists
    File: heap.c
    Line: 1217
    Routine: heap_create_with_catalog
42P07: relation "AspNetRoles" already exists
```

**Comment by khteh** [comment]
Fixed. Need to `INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")` the lines of the 2 `dotnet-ef migrations script`
